### ISSUE TITLE
Mouse clicks sluggish to execute, get out of order with keyboard commands

### ISSUE THREAD

**Issue by mbrock321** [stacks-task-manager/stacks#125] opened 2022-06-18 18:07 UTC
**Describe the bug**
I have noticed that it takes significantly longer for Stacks to respond to a mouse click, after upgrading from 1.8.2 to 1.9.1 -- to the point where a subsequent keyboard command will be executed before the preceding mouse click is acted on.

**To Reproduce**
1. Click on a task that is not currently selected
2. hit spacebar to toggle completion status
3. previously this worked fine, Now I have to pause before hitting the spacebar, or the completion status will toggle on whatever task was selected before I clicked on a new task.

**Expected behavior**
Mouse clicks and keyboard shortcuts should be processed in the order they are executed by the user. 

**Desktop (please complete the following information):**
OSX 10.14.6

**Comment by synapse** [comment] 2022-06-18 20:19
This was intended to prevent task selection when the user wants to open the task instead of selecting it. The selection is delayed by 200ms for this reason. 
If this becomes an issue and makes the app feel sluggish it will be removed in next version

**Comment by mbrock321** [comment] 2022-06-19 18:55
With this delay, I find that about half the time, when trying to mark a task as done, I wind up toggling the wrong task.  Then have to untoggle the wrongly selected one, click on the right one, wait, then toggle it.  Pretty frustrating.

I don't think I understand what purpose the delay is trying to achieve.  If I have one task selected and I double-click on a different task to open it, when I exit out of the task description, no task is selected.  So the delay doesn't seem to prevent losing the previous selection, if that was the intent.

**Comment by synapse** [comment] 2022-06-21 13:17
@mbrock321 should be fixed in [1.9.2](https://github.com/stacks-task-manager/stacks/releases/tag/v1.9.2)

**Closed** 2022-06-23 16:12 UTC
Labels: enhancement
